name: Flutter Lint and Quality Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Check formatting (KISS prensibi için önemli)
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Analyze for Code Smells
        run: flutter analyze
