name: Build and Publish Release APK

on:
  push:
    tags:
      - 'v*' # Sadece v1.0, v2.1 gibi "v" ile başlayan bir etiket atıldığında tetiklenir

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java for Android
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          generate_release_notes: true # Git commit mesajlarından otomatik sürüm notu oluşturur
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
